# Generated by Django 3.1.3 on 2020-11-29 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='NombreCompeto',
            new_name='NombreCompleto',
        ),
    ]
