# Generated by Django 3.1.3 on 2020-11-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='CURP',
            field=models.CharField(blank=True, max_length=18),
        ),
    ]
